# -*- coding: utf-8 -*-
"""Fix_FinalBikeSharing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t-P8K-UCtfZBZqpfLQzRWzPDvuT4A3sl
"""

!pip install streamlit


import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load data
from google.colab import files
uploaded = files.upload()

# Load data from csv files
finalbikesharing = pd.read_csv("hour.csv")

# Add a title
st.title('Dashboard Data Peminjaman Sepeda')

# Add a subtitle
st.markdown('Explorasi Data Peminjaman Sepeda di Kota X')

# Add a plot for rental count by season
season_rentals = finalbikesharing.groupby('season').mean()['cnt']
fig1, ax1 = plt.subplots()
ax1.bar(season_rentals.index, season_rentals.values)
ax1.set_xlabel('Musim')
ax1.set_ylabel('Total Transaksi')
ax1.set_title('Total Transaksi per musim')
st.pyplot(fig1)

# Add a plot for rental count by weather
weather_count = finalbikesharing.groupby('weathersit')['cnt'].sum()
fig2, ax2 = plt.subplots()
ax2.bar(weather_count.index, weather_count.values)
ax2.set_title('Total Transaksi per Cuaca')
ax2.set_xlabel('Cuaca')
ax2.set_ylabel('Total Transaksi')
st.pyplot(fig2)

# Add a plot for rental count by holiday/working day
holiday_count = finalbikesharing.groupby('holiday')['cnt'].sum()
fig3, ax3 = plt.subplots()
ax3.bar(holiday_count.index, holiday_count.values)
ax3.set_title('Total Transaksi pada Hari Libur dan hari kerja')
ax3.set_xlabel('Hari Libur (0 = hari kerja, 1 = Holiday / Weekend)')
ax3.set_ylabel('Total Transaksi')
st.pyplot(fig3)

# Add a plot for rental count by hour of the day
hour_count = finalbikesharing.groupby('hr')['cnt'].sum()
fig4, ax4 = plt.subplots()
ax4.plot(hour_count.index, hour_count.values)
ax4.set_title('Total Transaksi pada Setiap Jam')
ax4.set_xlabel('Jam')
ax4.set_ylabel('Total Transaksi')
st.pyplot(fig4)